/**
 * AUTO-GENERATED by scripts/sync-artifacts.mjs
 * DO NOT EDIT MANUALLY
 * Output: src/v0.1/index.ts
 */

export type { DigitalWastePassportShape } from "../generated/v0.1/digitalWastePassport.js";
export type { DigitalMarpolWastePassportShape } from "../generated/v0.1/digitalMarpolWastePassport.js";
export type { RecyclingOrganisationShape } from "../generated/v0.1/recycling.js";

export type SchemaKeyV01 = "dwp" | "dmwp" | "recycling";

export interface SchemaTypeMapV01 {
  "dwp": import("../generated/v0.1/digitalWastePassport.js").DigitalWastePassportShape;
  "dmwp": import("../generated/v0.1/digitalMarpolWastePassport.js").DigitalMarpolWastePassportShape;
  "recycling": import("../generated/v0.1/recycling.js").RecyclingOrganisationShape;
}

export type SchemaTypeV01<K extends SchemaKeyV01> = SchemaTypeMapV01[K];
