/**
 * AUTO-GENERATED by scripts/sync-artifacts.mjs
 * DO NOT EDIT MANUALLY
 * Output: src/v0.1/index.ts
 */

export type { DppUneceSchema } from "../generated/v0.1/dppUnece.js";
export * as DppUneceSchemaNS from "../generated/v0.1/dppUnece.js";
export type { DigitalWastePassportSchema } from "../generated/v0.1/digitalWastePassport.js";
export * as DigitalWastePassportSchemaNS from "../generated/v0.1/digitalWastePassport.js";
export type { DigitalMarpolWastePassportSchema } from "../generated/v0.1/digitalMarpolWastePassport.js";
export * as DigitalMarpolWastePassportSchemaNS from "../generated/v0.1/digitalMarpolWastePassport.js";
export type { RecyclingSchema } from "../generated/v0.1/recycling.js";
export * as RecyclingSchemaNS from "../generated/v0.1/recycling.js";
export type { EpcisEventsSchema } from "../generated/v0.1/epcisEvents.js";
export * as EpcisEventsSchemaNS from "../generated/v0.1/epcisEvents.js";

export type SchemaKeyV01 = "dpp-unece" | "dwp" | "dmwp" | "recycling" | "epcis-events";

export interface SchemaTypeMapV01 {
  "dpp-unece": import("../generated/v0.1/dppUnece.js").DppUneceSchema;
  "dwp": import("../generated/v0.1/digitalWastePassport.js").DigitalWastePassportSchema;
  "dmwp": import("../generated/v0.1/digitalMarpolWastePassport.js").DigitalMarpolWastePassportSchema;
  "recycling": import("../generated/v0.1/recycling.js").RecyclingSchema;
  "epcis-events": import("../generated/v0.1/epcisEvents.js").EpcisEventsSchema;
}

export type SchemaTypeV01<K extends SchemaKeyV01> = SchemaTypeMapV01[K];
