/**
 * AUTO-GENERATED by scripts/sync-artifacts.mjs
 * DO NOT EDIT MANUALLY
 * Output: src/current/index.ts
 */

export type { DppUneceSchema } from "../generated/current/dppUnece.js";
export * as DppUneceSchemaNS from "../generated/current/dppUnece.js";
export type { DigitalWastePassportSchema } from "../generated/current/digitalWastePassport.js";
export * as DigitalWastePassportSchemaNS from "../generated/current/digitalWastePassport.js";
export type { DigitalMarpolWastePassportSchema } from "../generated/current/digitalMarpolWastePassport.js";
export * as DigitalMarpolWastePassportSchemaNS from "../generated/current/digitalMarpolWastePassport.js";
export type { RecyclingSchema } from "../generated/current/recycling.js";
export * as RecyclingSchemaNS from "../generated/current/recycling.js";
export type { EpcisEventsSchema } from "../generated/current/epcisEvents.js";
export * as EpcisEventsSchemaNS from "../generated/current/epcisEvents.js";

export const CURRENT_BUILD_VERSION = "v0.1" as const;

export type SchemaKeyCurrent = "dpp-unece" | "dwp" | "dmwp" | "recycling" | "epcis-events";

export interface SchemaTypeMapCurrent {
  "dpp-unece": import("../generated/current/dppUnece.js").DppUneceSchema;
  "dwp": import("../generated/current/digitalWastePassport.js").DigitalWastePassportSchema;
  "dmwp": import("../generated/current/digitalMarpolWastePassport.js").DigitalMarpolWastePassportSchema;
  "recycling": import("../generated/current/recycling.js").RecyclingSchema;
  "epcis-events": import("../generated/current/epcisEvents.js").EpcisEventsSchema;
}

export type SchemaTypeCurrent<K extends SchemaKeyCurrent> = SchemaTypeMapCurrent[K];
