/**
 * AUTO-GENERATED by scripts/sync-artifacts.mjs
 * DO NOT EDIT MANUALLY
 * Output: src/current/index.ts
 */

export type { DigitalWastePassportShape } from "../generated/current/digitalWastePassport.js";
export type { DigitalMarpolWastePassportShape } from "../generated/current/digitalMarpolWastePassport.js";
export type { RecyclingOrganisationShape } from "../generated/current/recycling.js";

export const CURRENT_BUILD_VERSION = "v0.1" as const;

export type SchemaKeyCurrent = "dwp" | "dmwp" | "recycling";

export interface SchemaTypeMapCurrent {
  "dwp": import("../generated/current/digitalWastePassport.js").DigitalWastePassportShape;
  "dmwp": import("../generated/current/digitalMarpolWastePassport.js").DigitalMarpolWastePassportShape;
  "recycling": import("../generated/current/recycling.js").RecyclingOrganisationShape;
}

export type SchemaTypeCurrent<K extends SchemaKeyCurrent> = SchemaTypeMapCurrent[K];
